backend:
  # name: test-repo
  name: git-gateway
  repo: CodingWatchCollector/chez-mman-qr-code
  branch: production # Branch to update (optional; defaults to master)

media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: 'type de carte'
    name: 'menu-type'
    folder: 'src/assets/menu-type'
    slug: '{{day}}-{{month}}-{{hour}}-{{slug}}'
    editor:
      preview: false
    create: true
    fields:
      - {
          label: 'Type de carte',
          title: 'title',
          name: 'title',
          widget: 'string',
        }
      - {
          label: 'Active',
          name: 'active',
          widget: 'boolean',
          required: false,
          default: true,
        }
      - label: 'Contenu'
        name: 'content'
        widget: 'list'
        types:
          # - label: 'Formule'
          #   name: 'formula'
          #   widget: 'object'
          #   fields:
          #     - {
          #         label: 'Nom',
          #         title: 'title',
          #         name: 'title',
          #         widget: 'string',
          #     }
          #     - {
          #         label: 'Description',
          #         name: 'description',
          #         widget: 'string',
          #     }
          #     - {
          #        label: 'Prix', name: 'price', widget: 'string' }

          - label: 'A la carte'
            name: 'alacarte'
            widget: 'object'
            fields:
              - {
                  label: 'Nom',
                  title: 'title',
                  name: 'title',
                  widget: 'string',
                }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Prix',
                  name: 'price',
                  widget: 'string',
                  required: false,
                }
              - label: 'Plats:'
                name: 'item'
                widget: 'list'
                fields:
                  - { label: 'Nom', name: 'title', widget: 'string' }
                  - {
                      label: 'Description',
                      name: 'description',
                      widget: 'string',
                      required: false,
                    }
                  - {
                      label: 'Prix',
                      name: 'price',
                      widget: 'string',
                      required: false,
                    }
                  - {
                      label: 'Local',
                      name: 'local',
                      widget: 'boolean',
                      required: false,
                    }
                  - {
                      label: 'Vegetarien',
                      name: 'vegetarian',
                      widget: 'boolean',
                      required: false,
                    }

          - label: 'Menu'
            name: 'menu'
            widget: 'object'
            fields:
              - { label: 'Nom', name: 'title', widget: 'string' }
              - { label: 'Prix', name: 'price', widget: 'string' }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'string',
                  default: '1 Entrée + 1 Plat + 1 Fromage ou Dessert',
                  required: false,
                }
              - label: 'Entrées'
                name: 'starters'
                widget: 'object'
                fields:
                  - {
                      label: 'Nom',
                      name: 'title',
                      widget: 'string',
                      default: 'Entrées',
                    }
                  - label: 'Entrées:'
                    name: 'item'
                    widget: 'list'
                    fields:
                      - { label: 'Nom', name: 'title', widget: 'string' }
                      - {
                          label: 'Description',
                          name: 'description',
                          required: false,
                          widget: 'string',
                        }
                      - {
                          label: 'Supplement?',
                          name: 'supplement',
                          widget: 'string',
                          required: false,
                        }
                      - {
                          label: 'Local',
                          name: 'local',
                          widget: 'boolean',
                          required: false,
                        }
                      - {
                          label: 'Vegetarien',
                          name: 'vegetarian',
                          widget: 'boolean',
                          required: false,
                        }

              - label: 'Plats'
                name: 'main-course'
                widget: 'object'
                fields:
                  - {
                      label: 'Nom',
                      name: 'title',
                      widget: 'string',
                      default: 'Plats',
                    }
                  - label: 'Plats:'
                    name: 'item'
                    widget: 'list'
                    fields:
                      - { label: 'Nom', name: 'title', widget: 'string' }
                      - {
                          label: 'Description',
                          name: 'description',
                          required: false,
                          widget: 'string',
                        }
                      - {
                          label: 'Supplement?',
                          name: 'supplement',
                          required: false,
                          widget: 'string',
                        }
                      - {
                          label: 'Local',
                          name: 'local',
                          widget: 'boolean',
                          required: false,
                        }
                      - {
                          label: 'Vegetarien',
                          name: 'vegetarian',
                          widget: 'boolean',
                          required: false,
                        }

              - label: 'Desserts/Fromage'
                name: 'desert-cheese'
                widget: 'object'
                fields:
                  - {
                      label: 'Nom',
                      name: 'title',
                      widget: 'string',
                      default: 'Desserts/Fromage',
                    }
                  - label: 'Desserts/Fromage:'
                    name: 'item'
                    widget: 'list'
                    fields:
                      - { label: 'Nom', name: 'title', widget: 'string' }
                      - {
                          label: 'Description',
                          name: 'description',
                          required: false,
                          widget: 'string',
                        }
                      - {
                          label: 'Supplement?',
                          name: 'supplement',
                          required: false,
                          widget: 'string',
                        }
                      - {
                          label: 'Local',
                          name: 'local',
                          widget: 'boolean',
                          required: false,
                        }
                      - {
                          label: 'Vegetarien',
                          name: 'vegetarian',
                          widget: 'boolean',
                          required: false,
                        }
