backend:
#   name: test-repo
  name: git-gateway
  repo: CodingWatchCollector/chez-mman-qr-code
  branch: production # Branch to update (optional; defaults to master)

media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: 'type de menu'
    name: 'menu-type'
    folder: 'src/assets/menu-type'
    create: true
    fields:
      - { label: 'Title', title: 'title', name: 'title', widget: 'string' }

  - label: 'category'
    name: 'submenu'
    folder: 'src/assets/category'
    create: true
    fields:
      - { label: 'Title', title: 'title', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'markdown',
          required: false,
        }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - label: 'Item'
        name: 'item'
        widget: 'list'
        create: true
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: 'Price', name: 'price', widget: 'string' }

  - label: 'menu'
    name: 'menu'
    folder: 'src/assets/menu'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - label: 'Entrées'
        name: 'starters'
        create: true
        widget: 'object'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              default: 'Entrées',
            }
          - label: 'Item'
            name: 'item'
            create: true
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'markdown',
                }
              - { label: 'Price', name: 'price', widget: 'string' }
      - label: 'Plats'
        name: 'main-course'
        widget: 'object'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              default: 'Plats',
            }
          - label: 'Item'
            name: 'item'
            create: true
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'markdown',
                }
              - { label: 'Price', name: 'price', widget: 'string' }
      - label: 'Desserts/Fromage'
        name: 'desert-cheese'
        widget: 'object'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: 'string',
              default: 'Desserts/Fromage',
            }
          - label: 'Item'
            name: 'item'
            create: true
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {
                  label: 'Description',
                  name: 'description',
                  widget: 'markdown',
                }
              - { label: 'Price', name: 'price', widget: 'string' }
