backend:
  name: test-repo
  # name: git-gateway
  # branch: main # Branch to update (optional; defaults to master)

media_folder: 'images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'type de menu'
    label: 'menu-type'
    folder: 'assets/menu-type'
    create: true
    fields:
      - { label: 'Title', title: 'title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - label: 'category'
    name: 'submenu'
    folder: 'assets/category'
    create: true
    fields:
      - { label: 'Title', title: 'title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - label: 'menu'
    name: 'menu'
    folder: 'asssets/menu'
    create: true
    fields:
      - { label: 'Title', title: 'title', name: 'title', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
